workflows:
  android-release:
    name: Android Build
    environment:
      java: 17
    scripts:
      - cd android
      - chmod +x gradlew
      - ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
